<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link rel="stylesheet" href="/css/code_new_style.css">
    <script src="/js/submit_button.js"></script>
    <link rel="stylesheet"
          href="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/styles/default.min.css">
    <script src="//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.2.1/build/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body>
    <div id="input_and_submit">
        <textarea id="code_snippet" rows="25" cols="100" autofocus placeholder="write your code here"></textarea>
        <br>
        <button id="send_snippet" onclick="send()">Submit</button>
    </div>
</body>
</html>
